MONGODB_HOST: mongodb-{{ env }}.cloudops.store
REDIS_HOST: redis-{{ env }}.cloudops.store
CATALOGUE_HOST: catalogue-{{ env }}.cloudops.store
CART_HOST: cart-{{ env }}.cloudops.store
USER_HOST: user-{{ env }}.cloudops.store
RABBITMQ_HOST: rabbitmq-{{ env }}.cloudops.store
MYSQL_HOST: mysql-{{ env }}.cloudops.store
SHIPPING_HOST: shipping-{{ env }}.cloudops.store
PAYMENT_HOST: payment-{{ env }}.cloudops.store